namespace GG.Entity
{
    /// <summary>
    /// Generated Entity for Table : ADConfigColumns.
    /// </summary>
    public class ADConfigColumns
	{
		#region Generated By Column

		public int ADConfigColumnID { get; set; }

		public string AAStatus { get; set; }

		public string ADConfigColumnName { get; set; }

		public string ADConfigColumnCaption { get; set; }

		public int? ADConfigColumnVisibleIndex { get; set; }

		public string ADConfigColumnDataType { get; set; }

		public int? ADConfigColumnLength { get; set; }

		public bool? ADConfigColumnAllowEdit { get; set; }

		public bool? ADConfigColumnIsVisible { get; set; }

		public string ADConfigColumnDisplayFormat { get; set; }

		public string ADConfigColumnTableName { get; set; }

		public string ADConfigColumnFunctionCode { get; set; }

		public string ADConfigColumnDataSource { get; set; }

		public string ADConfigColumnDisplayMember { get; set; }

		public string ADConfigColumnValueMember { get; set; }

		public string ADConfigColumnFilter { get; set; }

		public int? ADConfigColumnWidth { get; set; }

		#endregion
	}
}