namespace GG.Entity
{
    /// <summary>
    /// Generated Entity for Table : ADConfigValues.
    /// </summary>
    public class ADConfigValues
	{
		#region Generated By Column

		public int ADConfigValueID { get; set; }

		public string AAStatus { get; set; }

		public string ADConfigKey { get; set; }

		public string ADConfigKeyValue { get; set; }

		public string ADConfigText { get; set; }

		public string ADConfigKeyDesc { get; set; }

		public string ADConfigKeyGroup { get; set; }

		public bool? IsActive { get; set; }

		#endregion
	}
}