namespace GG.Entity
{
    /// <summary>
    /// Generated Entity for Table : ADFieldColumns.
    /// </summary>
    public class ADFieldColumns
	{
		#region Generated By Column

		public int ADFieldColumnID { get; set; }

		public string AAStatus { get; set; }

		public int? ADFieldColumnWidth { get; set; }

		public int? ADFieldColumnVisibleIndex { get; set; }

		public bool? ADFieldColumnIsVisible { get; set; }

		public int? FK_ADConfigColumnID { get; set; }

		public int? FK_UserID { get; set; }

		public string ADFieldColumnFormName { get; set; }

		#endregion
	}
}