namespace GG.Entity
{
	/// <summary>
	/// Generated Entity for Table : ConfigValues.
	/// </summary>
	public class ConfigValues
	{
		#region Generated By Column

		public int ConfigValueID { get; set; }

		public string Status { get; set; }

		public string ConfigKey { get; set; }

		public string ConfigKeyValue { get; set; }

		public string ConfigText { get; set; }

		public string ConfigKeyDesc { get; set; }

		public string ConfigKeyGroup { get; set; }

		public bool? IsActive { get; set; }

		#endregion
	}
}