namespace GG.Entity
{
	/// <summary>
	/// Generated Entity for Table : FieldColumns.
	/// </summary>
	public class FieldColumns
	{
		#region Generated By Column

		public int FieldColumnID { get; set; }

		public string Status { get; set; }

		public int? FieldColumnWidth { get; set; }

		public int? FieldColumnVisibleIndex { get; set; }

		public bool? FieldColumnIsVisible { get; set; }

		public int? FK_ConfigColumnID { get; set; }

		public int? FK_UserID { get; set; }

		public string FieldColumnFormName { get; set; }

		#endregion
	}
}