namespace GG.Entity
{
	/// <summary>
	/// Generated Entity for Table : Modules.
	/// </summary>
	public class Modules
	{
		#region Generated By Column

		public int ModuleID { get; set; }

		public string Status { get; set; }

		public string ModuleNo { get; set; }

		public string ModuleName { get; set; }

		public int? ModuleWidth { get; set; }

		public int? ModuleHeight { get; set; }

		public string ModuleType { get; set; }

		public int? ModuleParentID { get; set; }

		public string ModuleCode { get; set; }

		public string ModuleLink { get; set; }

		public int? FK_SystemID { get; set; }

		#endregion
	}
}