namespace GG.Entity
{
	/// <summary>
	/// Generated Entity for Table : Systems.
	/// </summary>
	public class Systems
	{
		#region Generated By Column

		public int SystemID { get; set; }

		public string Status { get; set; }

		public string SystemNo { get; set; }

		public string SystemName { get; set; }

		#endregion
	}
}