namespace GG.Entity
{
	/// <summary>
	/// Generated Entity for Table : STModules.
	/// </summary>
	public class STModules
	{
		#region Generated By Column

		public int STModuleID { get; set; }

		public string AAStatus { get; set; }

		public string STModuleNo { get; set; }

		public string STModuleName { get; set; }

		public int STModuleWidth { get; set; }

		public int STModuleHeight { get; set; }

		public string STModuleType { get; set; }

		public int STModuleParentID { get; set; }

		public string STModuleCode { get; set; }

		public string STModuleLink { get; set; }

		public int FK_STSystemID { get; set; }

		#endregion
	}
}