namespace GG.Entity
{
	/// <summary>
	/// Generated Entity for Table : STSystems.
	/// </summary>
	public class STSystems
	{
		#region Generated By Column

		public int STSystemID { get; set; }

		public string AAStatus { get; set; }

		public string STSystemNo { get; set; }

		public string STSystemName { get; set; }

		#endregion
	}
}